### ISSUE TITLE
assignButton() and assignAxis() inside assert() don't get called on non-debug build

### ISSUE THREAD

**Issue by Raattis** [GuidoBisocoli/SFML_GamepadSupport#1]
assert() is defined empty on non-debug build causing these not to be called.

https://github.com/GuidoBisocoli/SFML_GamepadSupport/blob/9e7c4c0870fbf3ba5dbd6c2a01483a9fab4da6b6/Gamepad.cpp#L187
https://github.com/GuidoBisocoli/SFML_GamepadSupport/blob/9e7c4c0870fbf3ba5dbd6c2a01483a9fab4da6b6/Gamepad.cpp#L189

I'd also like to suggest adding a printf or `std::cerr << "Button not found: \"" << name << "\" \"" << data << "\""` to help with debugging.

A side note: I tripped this assert with a PS4 controller for touchpad button not being found. It might not be supported through XInput (instead the share button is handled like a normal button). If that's the case this probably should be an error instead of an assert.

Thanks for creating and making this library available. It's nice to use and makes SFML gamepad handling more bearable.

**Comment by GuidoBisocoli** [comment]
Thank you for helping!
